version: '3'
services:
    db: 
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: julius
        volumes:
            - /Users/Acer/AppData/Local/Postgres/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: julius-api
        restart: always
        build: .
        ports: 
            - "3000:3000"
        depends_on: 
            - db
            
  
  

      